name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'infra/**'
      - '.github/workflows/deploy-lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: sa-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7 # ou a versão que você estiver usando localmente

      - name: Empacotar Lambda
        run: |
          cd src
          zip -r ../deploy.zip .
          cd ..

      - name: Executar Terraform
        run: |
          cd infra
          terraform init -input=false
          terraform apply -auto-approve -input=false
