name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'infra/**'
      - '.github/workflows/deploy-lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: sa-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Empacotar Lambda
        run: |
          cd src
          zip -r ../deploy.zip .
          cd ..

      - name: Terraform Init
        run: |
          cd infra
          terraform init -input=false

      - name: Import Lambda existente (se houver)
        run: |
          cd infra
          # tenta importar a Lambda; se já importada ou não existir, ignora erro
          terraform import aws_lambda_function.fastfood_lambda fastfood-lambda || true

      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve -input=false
